# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
 
trigger:
- test
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
- group: App-project
stages:
- stage: demostage
  jobs:
  - job: Test
    steps:
    - script: echo $(secret)